getwd()
dir.create("raw_data")
dir.create("clean_data")
dir.create("scripts")
dir.create("results")
dir.create("plots")
data <- read.csv(file.choose())
View(data)
str(data)
data$gender <- as.factor(data$gender)
class(data$gender)
data$diagnosis <- as.factor(data$diagnosis)
class(data$diagnosis)

data$smoker <- ifelse(tolower(data$smoker) == "yes", 1, 0)

data$smoker <- factor(data$smoker)
class(data$smoker)
str(data$smoker)
View(data)
levels(data$smoker)    
str(data$smoker)  
write.csv(data, "clean_data/patient_info_clean.csv")
save.image(file = "JomanaMahmoudElsaghier_Class_Ib_Assignment.RData")